# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details
version: 2
formats: [htmlzip]
sphinx:
  configuration: docs/conf.py
python:
  install:
    - requirements: requirements.txt
build:
  os: ubuntu-lts-latest
  tools:
    python: "3.14"
  commands:
    - pip install --upgrade pip
    - pip install -e '.[docs]'
    - pip install nbsphinx
    - pip install sphinxcontrib.bibtex
    # Make sure RTD can find the html output
    - sphinx-apidoc -f -o docs src/estatjp
    - sphinx-build -M html docs/ _readthedocs/
