name: Build Docs

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  build-docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.5.2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v5.1.0
        with:
            python-version: ${{ matrix.python-version }}

      - name: Setup pandoc
        uses: r-lib/actions/setup-pandoc@4f58f8ffa872cbd4cb016c51ec497fdbe0a02711 #v2
        with:
          pandoc-version: '3.1.11' # The pandoc version to download (if necessary) and use.

      - name: Test pandoc
        run: echo "# Test" | pandoc -t html

      - name: Install sphinx-autoapi
        run: |
            python -m pip install --upgrade pip
            python -m pip install sphinx-autoapi==0.7.1

      - name: Install autobuild
        run: |
            python -m pip install sphinx-autobuild

      - name: Install sphinxcontrib-bibtex
        run: |
            python -m pip install sphinxcontrib-bibtex

      - name: Install ipython
        run: |
            python -m pip install notebook
            python -m pip install ipkernel
            python -m pip install ipython==9.11.0
            python -m pip install ipython-pygments-lexers
            
      - name: Install myst-parser
        run: |
            python -m pip install myst-parser

      - name: Install nbsphinx
        run: |
            python -m pip install nbsphinx

      - name: Install hatch
        run: |
            python -m pip install hatch

      - name: Build documentation using Hatch
        run: |
            hatch run docs:build
